# -*- coding: utf-8 -*-
"""BigEarthNet CNN for uniquely labelled 46 classes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/119rRHSflum0Dv2It9Vuco6A6nGlcddxw

BigEarthNet unique labelled data with 46 classes uploaded on google drive.
Step  1: to create geotiff image using 12 bands of Sentinel-2 imagery **bold text**
"""

import os
import pandas as pd

src_path = '/content/drive/MyDrive/BigEarthNet unique labelled'

!pip install rasterio

import rasterio
from rasterio import merge
def merge_bands(path,sub):
    search = '*B*.tif'   # 12 Band files end with B01,B02....
    files_batch = []
    files_batch = glob.glob(os.path.join(path,search)) #search all tif band files 
    files_batch =sorted(files_batch)
    print(files_batch) 
    print(len(files_batch))
    # Read metadata of first file
    with rasterio.open(files_batch[0]) as src0: #open first files out of batch of 12 files
        meta = src0.meta

    # Update meta to reflect the number of layers in merged output geotiff file
    meta.update(count = len(files_batch)) #change output meta files as it will have 12 bands rather than 1 as in source files

    # Read each layer and write it to stack
    fnames = path +'/' + sub + '.tif'
    with rasterio.open(fnames, 'w', **meta) as dst: #output/destination(dst) file opened in write mode with an extra "meta" arbitrary keyword argument
        print(dst)
        for id, layer in enumerate(files_batch, start=1): # create list of 12 tuples 
            print(id,layer)
            with rasterio.open(layer) as src1:
                dst.write_band(id, src1.read(1)) #read 1 band at a time and write it to stacled tif

dirs = os.listdir(src_path)  #list of all classes
dirs

import glob
for dir in dirs:
  sub_dirs = os.listdir(os.path.join(src_path,dir))
  print(dir,len(sub_dirs))
  for data_folder in sub_dirs:
    path=os.path.join(src_path,dir)
    merge_bands(path,data_folder)

